baseURL: https://www.hyperdrivecodes.com
title: Hyperdrive Website Development

params:
  description: Hyperdrive exists to develop high-end bespoke website solutions for your business or brand.hyperdrivecodes

menu:
  main:
  - identifier: home
    name: Home
    pre: <i class="fa-solid fa-house-day" name="house-icon"></i>
    url: /
    weight: 1

#  - identifier: about
#    name: About
#    pre: <i class="fa-solid fa-rocket-launch"></i>
#    url: /
#    weight: 2

#  - identifier: portfolio
#    name: Portfolio
#    pre: <i class="fa-solid fa-display-code"></i>
#    url: /
#    weight: 3

  - identifier: contact
    name: Contact
    pre: <i class="fa-solid fa-comment-arrow-up-right"></i>
    url: /
    weight: 4